-- Migration: Notifications System
-- Created: 2026-07-04
-- Description: Creates notifications table for real-time notification system

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  entity_type VARCHAR(50),
  entity_id BIGINT,
  read BOOLEAN NOT NULL DEFAULT FALSE,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON public.notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON public.notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_entity ON public.notifications(entity_type, entity_id);

-- Comentários
COMMENT ON TABLE public.notifications IS 'Sistema de notificações em tempo real para eventos importantes';
COMMENT ON COLUMN public.notifications.type IS 'Tipos: comment, status_change, new_opportunity, deadline_approaching, chat_message, approval_pending';
COMMENT ON COLUMN public.notifications.entity_type IS 'Tipo da entidade relacionada: project, opportunity, review, client, etc';
COMMENT ON COLUMN public.notifications.entity_id IS 'ID da entidade relacionada';
COMMENT ON COLUMN public.notifications.metadata IS 'Dados adicionais em formato JSON para contexto da notificação';
