-- Workspace foundation for the unified producer/filmmaker model.
-- This keeps the current user-owned data model intact while creating the
-- tenant layer that future migrations can attach projects, clients and files to.

create table if not exists public.workspaces (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'solo',
  owner_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_members (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  invited_email text,
  invited_by_user_id bigint references public.users(id) on delete set null,
  role text not null default 'member',
  status text not null default 'active',
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, user_id)
);

create index if not exists idx_workspaces_owner_user_id on public.workspaces(owner_user_id);
create index if not exists idx_workspace_members_workspace_id on public.workspace_members(workspace_id);
create index if not exists idx_workspace_members_user_id on public.workspace_members(user_id);
create index if not exists idx_workspace_members_invited_email on public.workspace_members(invited_email);

alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;

drop policy if exists "Workspace members can read their workspaces" on public.workspaces;
create policy "Workspace members can read their workspaces"
on public.workspaces for select
to authenticated
using (
  exists (
    select 1
    from public.workspace_members wm
    join public.users u on u.id = wm.user_id
    where wm.workspace_id = workspaces.id
      and wm.status = 'active'
      and u.supabase_id = auth.uid()
  )
);

drop policy if exists "Owners can create own workspaces" on public.workspaces;
create policy "Owners can create own workspaces"
on public.workspaces for insert
to authenticated
with check (
  exists (
    select 1
    from public.users u
    where u.id = workspaces.owner_user_id
      and u.supabase_id = auth.uid()
  )
);

drop policy if exists "Workspace admins can update workspaces" on public.workspaces;
create policy "Workspace admins can update workspaces"
on public.workspaces for update
to authenticated
using (
  exists (
    select 1
    from public.workspace_members wm
    join public.users u on u.id = wm.user_id
    where wm.workspace_id = workspaces.id
      and wm.status = 'active'
      and wm.role in ('owner', 'admin')
      and u.supabase_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.workspace_members wm
    join public.users u on u.id = wm.user_id
    where wm.workspace_id = workspaces.id
      and wm.status = 'active'
      and wm.role in ('owner', 'admin')
      and u.supabase_id = auth.uid()
  )
);

drop policy if exists "Workspace members can read memberships" on public.workspace_members;
create policy "Workspace members can read memberships"
on public.workspace_members for select
to authenticated
using (
  exists (
    select 1
    from public.workspace_members my_membership
    join public.users u on u.id = my_membership.user_id
    where my_membership.workspace_id = workspace_members.workspace_id
      and my_membership.status = 'active'
      and u.supabase_id = auth.uid()
  )
);

drop policy if exists "Workspace admins can manage memberships" on public.workspace_members;
create policy "Workspace admins can manage memberships"
on public.workspace_members for all
to authenticated
using (
  exists (
    select 1
    from public.workspace_members my_membership
    join public.users u on u.id = my_membership.user_id
    where my_membership.workspace_id = workspace_members.workspace_id
      and my_membership.status = 'active'
      and my_membership.role in ('owner', 'admin')
      and u.supabase_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.workspace_members my_membership
    join public.users u on u.id = my_membership.user_id
    where my_membership.workspace_id = workspace_members.workspace_id
      and my_membership.status = 'active'
      and my_membership.role in ('owner', 'admin')
      and u.supabase_id = auth.uid()
  )
);

with users_without_workspace as (
  select u.id, coalesce(nullif(trim(u.studio_name), ''), nullif(trim(u.name), ''), split_part(u.email, '@', 1), 'Meu Studio') as workspace_name
  from public.users u
  where not exists (
    select 1
    from public.workspace_members wm
    where wm.user_id = u.id
      and wm.status = 'active'
  )
),
created_workspaces as (
  insert into public.workspaces (name, type, owner_user_id)
  select workspace_name, 'solo', id
  from users_without_workspace
  returning id, owner_user_id
)
insert into public.workspace_members (workspace_id, user_id, role, status, accepted_at)
select id, owner_user_id, 'owner', 'active', now()
from created_workspaces
where owner_user_id is not null
on conflict (workspace_id, user_id) do nothing;
