-- FRAME/Cena Studio operational schema for Supabase Postgres.
-- Mirrors the current SQLite runtime schema so the remote database can be
-- prepared before switching the server persistence layer.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  role text not null default 'user',
  name text,
  avatar_url text,
  email_verified boolean not null default false,
  github_id text,
  supabase_id uuid unique references auth.users(id) on delete set null,
  studio_name text,
  studio_role text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.tools (
  id text primary key,
  name text not null,
  description text,
  category text,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.generations (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  tool_id text references public.tools(id),
  project_id bigint,
  input text,
  output text,
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  type text not null default 'contact',
  created_at timestamptz not null default now()
);

create table if not exists public.plans (
  id text primary key,
  name text not null,
  price_brl integer not null,
  generation_limit integer not null,
  features jsonb not null default '[]'::jsonb
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  plan_id text not null references public.plans(id),
  status text not null default 'active',
  trial_ends_at timestamptz,
  current_period_start timestamptz not null default now(),
  current_period_end timestamptz,
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.usage (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  tool_id text not null,
  period text not null,
  count integer not null default 0,
  unique(user_id, tool_id, period)
);

create table if not exists public.reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used boolean not null default false
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  company text,
  email text,
  phone text,
  segment text not null default 'direct',
  status text not null default 'lead',
  workflow_stage text not null default 'prospect',
  notes text,
  total_spent integer not null default 0,
  first_contact_at timestamptz,
  last_contact_at timestamptz,
  address text,
  city text,
  state text,
  country text,
  website text,
  linkedin text,
  instagram text,
  industry text,
  company_size text,
  annual_revenue integer,
  contact_person text,
  contact_role text,
  billing_cycle text,
  payment_method text,
  tax_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  name text not null,
  description text,
  status text not null default 'active',
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'generations_project_id_fkey'
      and conrelid = 'public.generations'::regclass
  ) then
    alter table public.generations
      add constraint generations_project_id_fkey
      foreign key (project_id) references public.projects(id) on delete set null;
  end if;
end $$;

create table if not exists public.project_states (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  tool_id text not null,
  form_data jsonb,
  output_data text,
  updated_at timestamptz not null default now(),
  unique(project_id, tool_id)
);

create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  title text not null,
  stage text not null default 'prospect',
  estimated_value integer,
  probability integer not null default 50,
  expected_close_date date,
  lost_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  type text,
  subject text,
  notes text,
  next_follow_up timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.collaborators (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  email text not null,
  role text not null default 'member',
  phone text not null default '',
  skills text,
  daily_rate integer not null default 0,
  status text not null default 'active',
  availability text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  collaborator_id bigint references public.collaborators(id) on delete cascade,
  role text not null default 'member',
  permissions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  filename text not null,
  original_name text not null,
  mime_type text,
  size integer,
  path text not null,
  category text not null default 'general',
  created_at timestamptz not null default now()
);

create table if not exists public.video_reviews (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  file_id bigint references public.files(id) on delete set null,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  description text,
  status text not null default 'draft',
  share_token text unique,
  expires_at timestamptz,
  video_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.video_comments (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.video_reviews(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  author_name text not null,
  timestamp_seconds double precision not null,
  comment text not null,
  annotations jsonb not null default '[]'::jsonb,
  resolved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'info',
  read boolean not null default false,
  link text,
  created_at timestamptz not null default now()
);

create table if not exists public.financial_entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  kind text not null check(kind in ('income', 'expense')),
  description text not null,
  category text not null default 'geral',
  amount integer not null default 0,
  status text not null default 'pending' check(status in ('pending', 'settled', 'canceled')),
  due_date date,
  paid_at timestamptz,
  recurrence text not null default 'once' check(recurrence in ('once', 'monthly')),
  is_fixed boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.studio_settings (
  user_id bigint primary key references public.users(id) on delete cascade,
  studio_name text not null default 'Cena Studio',
  legal_name text not null default '',
  document text not null default '',
  email text not null default '',
  phone text not null default '',
  city text not null default '',
  website text not null default '',
  signature text not null default 'Responsavel comercial',
  primary_color text not null default '#ff4d1d',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users(email);
create index if not exists idx_users_github_id on public.users(github_id);
create index if not exists idx_users_supabase_id on public.users(supabase_id);
create index if not exists idx_projects_user_id on public.projects(user_id);
create index if not exists idx_projects_client_id on public.projects(client_id);
create index if not exists idx_projects_status on public.projects(status);
create index if not exists idx_clients_user_id on public.clients(user_id);
create index if not exists idx_clients_status on public.clients(status);
create index if not exists idx_generations_user_id on public.generations(user_id);
create index if not exists idx_generations_tool_id on public.generations(tool_id);
create index if not exists idx_generations_project_id on public.generations(project_id);
create index if not exists idx_generations_created_at on public.generations(created_at);
create index if not exists idx_project_states_project_id on public.project_states(project_id);
create index if not exists idx_interactions_client_id on public.interactions(client_id);
create index if not exists idx_interactions_user_id on public.interactions(user_id);
create index if not exists idx_opportunities_user_id on public.opportunities(user_id);
create index if not exists idx_opportunities_client_id on public.opportunities(client_id);
create index if not exists idx_opportunities_stage on public.opportunities(stage);
create index if not exists idx_files_project_id on public.files(project_id);
create index if not exists idx_files_user_id on public.files(user_id);
create index if not exists idx_video_reviews_project_id on public.video_reviews(project_id);
create index if not exists idx_video_reviews_share_token on public.video_reviews(share_token);
create index if not exists idx_video_comments_review_id on public.video_comments(review_id);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_read on public.notifications(read);
create index if not exists idx_collaborators_user_id on public.collaborators(user_id);
create index if not exists idx_project_members_project_id on public.project_members(project_id);
create index if not exists idx_project_members_collaborator_id on public.project_members(collaborator_id);
create index if not exists idx_financial_entries_user_id on public.financial_entries(user_id);
create index if not exists idx_financial_entries_due_date on public.financial_entries(due_date);
create index if not exists idx_financial_entries_status on public.financial_entries(status);
create index if not exists idx_reset_tokens_token on public.reset_tokens(token);
create index if not exists idx_subscriptions_user_id on public.subscriptions(user_id);
create index if not exists idx_studio_settings_user_id on public.studio_settings(user_id);

insert into public.plans (id, name, price_brl, generation_limit, features) values
  ('free', 'Free', 0, 5, '["5 geracoes/mes","Acesso a 6 ferramentas","Export .txt"]'::jsonb),
  ('pro', 'Pro', 4900, 50, '["50 geracoes/mes","Fluxos principais de producao","Export PDF e DOCX","Historico completo"]'::jsonb),
  ('studio', 'Studio', 9900, -1, '["Geracoes ilimitadas","Fluxos principais de producao","Projetos e pastas","Suporte prioritario"]'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  price_brl = excluded.price_brl,
  generation_limit = excluded.generation_limit,
  features = excluded.features;

insert into public.tools (id, name, description, category, is_active) values
  ('01', 'Gerador de Roteiro', 'Roteiros formatados para producao audiovisual.', 'Pre-producao', true),
  ('02', 'Decupagem Tecnica', 'Planos, movimentos, lentes e planejamento tecnico.', 'Direcao', true),
  ('03', 'Callsheet Inteligente', 'Contatos, horarios, locacoes e necessidades do set.', 'Producao', true),
  ('04', 'Orcamento Automatico', 'Orcamentos realistas para equipe, equipamento e pos.', 'Comercial', true),
  ('05', 'Proposta Comercial', 'Escopo, cronograma, valores e termos comerciais.', 'Vendas', true),
  ('06', 'Contratos', 'Rascunhos de contrato e documentos juridicos de apoio.', 'Juridico', true),
  ('07', 'Briefing Inteligente', 'Organizacao de informacoes do cliente antes da producao.', 'Atendimento', true),
  ('08', 'Moodboard & Look', 'Direcao visual, paleta e referencias.', 'Criativo', true),
  ('09', 'Checklist de Producao', 'Listas operacionais para pre, set e entrega.', 'Producao', true),
  ('10', 'Cronograma', 'Marcos, datas, dependencias e rodadas de aprovacao.', 'Producao', true),
  ('11', 'Relatorio de Entrega', 'Resumo de materiais finais e aceite do cliente.', 'Entrega', true),
  ('12', 'Assistente Livre', 'Assistente geral para producao audiovisual.', 'Assistente', true)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  is_active = excluded.is_active,
  updated_at = now();
